# Generated by Django 3.0 on 2021-04-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Medicinist'), (2, 'Org'), (3, 'Anonymous')], default=3, max_length=5),
        ),
    ]
